# app.yaml

runtime: nodejs20
entrypoint: npm start

# — if you want your database creds available at runtime —
env_variables:
  DB_HOST:     127.0.0.1
  DB_PORT:     "3307"
  DB_USER:     root
  DB_PASSWORD: A23411393o
  DB_NAME:     c2_tennis_academy

automatic_scaling:
  min_instances: 1
  max_instances: 5


